## replace diana with the user on your computer
user: "{{ host_user }}"

#
# Miscellaneous
#

# whether to enable bluetooth or not
# true or false
enable_bluetooth: true

# Audio Server
# Weather to use pipewire or pluseaudio
# pipewire or pluseaudio
audio_server: pipewire

# Framework Laptop Intel 13 Inch fix fn keys,brightness,sound buttons
# true or false
framework_laptop_intel_13inch: true

default_shell: zsh  # Change to the desired default shell, e.g., zsh or bash

icons:
  cursor_icons_package: bibata-cursor-theme-bin # AUR ONLY CURRENTLY
  cursor_icons_theme: Bibata-Modern-Ice

pacman:
  parallel_downloads: 5 # Adjust as needed
  enable_multilib: false  # Set to false if you don't want to enable multilib
  # set aur helper
  # supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
  aur_helper: yay
   
default_roles:
  - system
  - bluetooth
  - audio
  - zsh
  - oh-my-posh
  - fastfetch
  - helix
  - alacritty
  - nautilus
  - hyprland
  - ags
  - firefox
  - greetd
  - mission-center
  - zed
  - sunroof #vencord fork discord client
  - spotube #spotify open source client

