## replace diana with the user on your computer
#user: "{{ host_user }}"
user: "{{ ansible_env['USER']}}"

system:
  # whether to enable bluetooth or not
  # true or false
  enable_bluetooth: true

  # whether to install and enable bluetooth-autoconnect or not
  # true or false
  enable_bluetooth_autoconnect: true

  # Audio Server
  # Weather to use pipewire or pluseaudio
  # pipewire or pulseaudio
  audio_server: pipewire

  gtk:
    # Change what gtk window buttons are shown
    # Options: :, close:, minimize:, maximize:, close,minimize: close,maximize:, manimize,maximize, or close,minimize,maximize:
    buttons: ":"

  # Headers package for your kernel
  # Required for VMware Workstation
  # Use the exact package name if you want to use the said hypervisor
  headers_package: linux-headers

  hyprland:
    # Support for autostart entries from XDG, provided by dex
    #
    # Setting this to false will stop such entries from working and
    # you will have to add apps you want to launch on boot as exec-once
    # entries in ~/.config/hypr/config/autostart.conf.
    #
    # See #52 for a deeper lore into this.
    #
    # true or false
    xdg_autostart: false

    plugins:
      # Master switch for Hyprland plugins
      # The Hyprland package on official Arch repo is currently broken that
      # breaks "hyprpm", which is what we use to install the plugins.
      # Uncommenting this is not a good idea unless you rebuild the package
      # with the proposed fix beforehand.
      # See dianaw353/dotfiles#53 for more info.
      # true or false
      enabled: false

      # List of URLs to install Hyprland plugins from
      # These URLs will each be passed to "hyprpm add" directly and
      # iterated through. Comments at the end of URLs are fine.
      list:
        - https://github.com/virtcode/hypr-dynamic-cursors # dynamic-cursors

i18n:
  # Supplementary fonts
  fonts:
    - cjk # Noto Chinese-Japanese-Korean
    - ja # Japanese outline font by IPA, Japan
    - tok # toki pona - sitelen pona

  # IMEs for fcitx5
  imes:
    - zh # Chinese - Pinyin
    - ja # Japanese - Mozc
    - ko # Korean - Hangul
    - tok # toki pona - ilo sitelen

gpu:
  # Nvidia users, buckle up!
  # Whether to use the proprietary Nvidia drivers or to keep the open source Nouveau drivers
  # Beware that usage of the proprietary drivers, which are out of tree, WILL TAINT THE KERNEL!
  # Also make sure to read the Arch Wiki to make sure the series you have is supported by the latest "nvidia" package.
  # Failure to do so will KILL your dGPU ALTOGETHER UNTIL YOU FIX IT OR PERFORM A REINSTALL!
  # This flag is for NVIDIA and AMD but, not for intel as it dose not have proprietary drivers
  # true or false
  proprietary_drivers: false
  

icons:
  cursor_icons_package: bibata-cursor-theme-bin # AUR ONLY CURRENTLY
  cursor_icons_theme: Bibata-Modern-Ice
  # available cursor sizes: 16 20 22 24 28 32 40 48 56 64 72 80 88 96
  cursor_icons_size: 24
  system_icons_package: tela-circle-icon-theme-all # AUR ONLY CURRENTLY
  system_icons_theme: Tela-circle-pink
  
pacman:
  parallel_downloads: 5 # Adjust as needed
  enable_multilib: true  # If you want to use 32bit code, NEEDED for 32-bit drivers and gaming
  # set aur helper
  # supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
  aur_helper: yay
  # Option to enable the chaotic-aur: https://aur.chaotic.cx/ or keep it disabled
  # true of false 
  chaotic_aur: false

pre_tasks:
  - package_manager
  - detect_vm
  - drivers
  - laptop_workarounds
  - system

default_roles:
  - ags
  - hyprland
  - core_apps
  - i18n # Internationlization. Ex. fcitx5, supplementary fonts
  - custom_apps
  # - kvm # Virtal Machine setup
  # - vmware # VMware Workstation - Type 2 hypervisor alternative to KVM
  - gaming

post_tasks:
  - package_cleanup

# TODO: In future this will be able to change hyprland keybinds to open these applications
core_packages: # outside of WM/DE dependencies
    - wezterm-git # terminal
    - zen-browser-bin # browser
    - fastfetch # neofetch alternitive
    - nautilus # file explorer
    - zed # Visual studio alternitive
    - zsh # if zsh it would install my configuration and would also install zoxide, fzf, eza, zinit, and oh-my-posh
    - helix # text editor
    - ttf-dejavu-nerd
    - mission-center # System Monitor
    - noto-fonts
    - noto-fonts-emoji
    - noto-fonts-extra

# user prefered packages outside of core_packages
user_packages:
    - github-cli
    - android-tools
    - spotube-bin
    - vesktop-bin

# Games
# Needs pacman.enable_multilib to be set to true
gaming:
  compatibility_layer:
    - wine
    - winetricks
    - dxvk-bin
    - vkd3d
    - lib32-gnutls
    - steam-native-runtime
  utilities:
    # - bottles
    - protonplus
    - gamescope
    - mangohud
    - lib32-mangohud
    - goverlay
  launchers:
    # Will install 4 versions of java for compatibility for all versions of minecraft alongside prism launcher
    - prismlauncher
    - steam
    - heroic-games-launcher-bin
    - lutris
