---
- name: Framework Laptop Workarounds
  block:
    - name: Framework Laptop 13 autobrightness/keybind fix
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      when:
        - board_vendor == 'Framework'
      loop:
        - iio-sensor-proxy 
