---
- name: "Ags | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: ags_distribution_config

- name: "Ags | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: ags_distribution_config.stat.exists

- name: Configure Ags Greetd
  block:
    - name: Create greetd configuration directory
      file:
        path: /etc/greetd
        state: directory
      become: true

    - name: "Ags Greetd Configuration | Update configuration templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/etc/greetd/{{ item.dest }}"
        backup: no
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      loop:
        - { src: 'config.toml.j2', dest: 'config.toml' }

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
      become: true
      with_items:
        - greetd

    - name: Create directories and set ownership
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      become: true
      loop:
        - { path: '/var/cache/greeter', owner: 'greeter', group: 'greeter', mode: '0755' }

    - name: Ags user config - Agsv1
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      when:
        - system.ags.versions is defined
        - "'v1' in system.ags.versions"
      loop:
        - { src: "ags", dest: "{{ ansible_user_dir }}/.config/" }

    - name: Ags user config - Agsv2
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      when:
        - system.ags.versions is defined
        - "'v2' in system.ags.versions"
      loop:
        - { src: "agsv2", dest: "{{ ansible_user_dir }}/.config/" }

    - name: Ags user config - Favorites
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ ansible_user_dir }}/.config/{{ item.version }}/lib/favorites.ts"
        backup: no
      become: false
      when:
        - system.ags.versions is defined
        - system.ags.favorites is defined
      loop:
        - { src: "favorites.ts.j2", version: "ags" }

    - name: Get the name for keybound terminal app
      ansible.builtin.shell:
        cmd: |
          grep "Name=" $(grep -r {{ system.hyprland.shortcut_apps.terminal }} /usr/share/applications | sed "s/:.*//" | uniq | head -n1) | head -n1 | sed "s/.*=//"
      register: terminal_app_name

    - name: Get the name for keybound web browser
      ansible.builtin.shell:
        cmd: |
          grep "Name=" $(grep -r {{ system.hyprland.shortcut_apps.browser }} /usr/share/applications | sed "s/:.*//" | uniq | head -n1) | head -n1 | sed "s/.*=//"
      register: browser_app_name

    - name: Get the name for keybound file manager
      ansible.builtin.shell:
        cmd: |
          grep "Name=" $(grep -r {{ system.hyprland.shortcut_apps.file_manager }} /usr/share/applications | sed "/autorun/d; /cache/d; s/:.*//" | uniq | head -n1) | head -n1 | sed "s/.*=//"
      register: fm_app_name

    - name: Get the name for system monitor app
      ansible.builtin.shell:
        cmd: |
          grep "Name=" $(grep -r {{ system.hyprland.shortcut_apps.system_monitor }} /usr/share/applications | sed "s/:.*//" | uniq | head -n1) | head -n1 | sed "s/.*=//"
      register: three_finger_salute_app_name

    - name: Ags user config - Shortcuts
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ ansible_user_dir }}/.config/{{ item.version }}/widget/keybinds/data/shortcuts.ts"
        backup: no
      become: false
      when:
        - system.ags.versions is defined
        - "'v1' in system.ags.versions"
        - "'v2' in system.ags.versions"
      loop:
        - { src: "shortcuts.ts.j2", version: "ags" }

    - name: Ags system config - Agsv1
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      when:
        - system.ags.versions is defined
        - "'v1' in system.ags.versions"
      loop:
        - { src: "ags", dest: "/etc/greetd/" }
      become: true

    - name: Ags system config - Agsv2
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      when:
        - system.ags.versions is defined
        - "'v2' in system.ags.versions"
        - "not 'v1' in system.ags.versions"
      loop:
        - { src: "agsv2", dest: "/etc/greetd/" }
      become: true

- name: Manage User Pictures
  block:
    - name: Synchronize pictures
      ansible.posix.synchronize:
        mode: push
        src: "{{ playbook_dir }}/assets/{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      become: true
      loop:
        - { src: 'Wallpapers', dest: '{{ ansible_user_dir }}/Pictures/' }
        - { src: 'Wallpapers/mountain.png', dest: '/var/cache/greeter/background' }
        - { src: 'pfp', dest: '{{ ansible_user_dir }}/Pictures' }
        - { src: 'Wallpapers/mountain.png', dest: '{{ ansible_user_dir }}/.config/background' }
    
    - name: Download additional wallpapers
      ansible.builtin.shell:
        cmd: |
          cd {{ ansible_user_dir }}/Pictures/Wallpapers/
          for i in $(curl "https://api.github.com/repos/"{{ item.repo }}"/git/trees/"{{ item.tree }}"?recursive=1" | jq -r '.tree.[].path' | grep {{ item.path }}"/"); do
            curl --remote-name https://raw.githubusercontent.com/{{ item.repo }}/{{ item.tree }}/$i
          done
      become: false
      changed_when: no
      loop: "{{ system.ags.wallpaper_repos }}"

    - name: Synchronize ags system configuration files
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      become: true
      loop:
        - { src: '{{ ansible_user_dir }}/Pictures/pfp/avatar.jpg', dest: '/var/lib/AccountsService/icons/{{ user }}' }
