---
- name: "Ags | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: ags_distribution_config

- name: "Ags | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: ags_distribution_config.stat.exists

- name: Configure Ags Greetd
  block:
    - name: Create greetd configuration directory
      file:
        path: /etc/greetd
        state: directory
      become: true

    - name: "Ags Greetd Configuration | Update configuration templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/etc/greetd/{{ item.dest }}"
        backup: no
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      loop:
        - { src: 'config.toml.j2', dest: 'config.toml' }

    - name: "Ags Greetd Configuration | Set up the environment"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/etc/{{ item.dest }}"
        backup: yes
        owner: "root"
        group: "root"
      become: true
      loop:
        - { src: 'environment.j2', dest: 'environment' }

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
      become: true
      with_items:
        - greetd

    - name: Create directories and set ownership
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      become: true
      loop:
        - { path: '/var/cache/greeter', owner: 'greeter', group: 'greeter', mode: '0755' }
        
    - name: Ags user config - Agsv1
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      when:
        - system.ags.version is defined
        - system.ags.version == "v1" or system.ags.version == "both"
      loop:
        - { src: "ags", dest: "{{ ansible_user_dir }}/.config/" }
        
    - name: Ags user config - Agsv2
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      when:
        - system.ags.version is defined
        - system.ags.version == "v2"
      loop:
        - { src: "agsv2", dest: "{{ ansible_user_dir }}/.config/" }

    - name: Ags user config - Shortcuts
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ ansible_user_dir }}/.config/{{ item.version }}/widget/keybinds/data/shortcuts.ts"
        backup: no
      become: false
      when:
        - system.ags.version is defined
        - system.ags.version == "both"
      loop:
        - { src: "shortcuts.ts.j2", version: "ags" }
        - { src: "shortcuts.ts.j2", version: "agsv2" }
        
    - name: Ags system config - Agsv1
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      when:
        - system.ags.version is defined
        - system.ags.version == "v1" or system.ags.version == "both"
      loop:
        - { src: "ags", dest: "/etc/greetd/" }
      become: true

    - name: Ags system config - Agsv2
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      when:
        - system.ags.version is defined
        - system.ags.version == "v2"
      loop:
        - { src: "agsv2", dest: "/etc/greetd/" }
      become: true

- name: Manage User Pictures
  block:
    - name: "Synchronize pictures"
      ansible.posix.synchronize:
        mode: push
        src: "{{ playbook_dir }}/assets/{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      become: true
      loop:
        - { src: 'Wallpapers', dest: '{{ ansible_user_dir }}/Pictures/' }
        - { src: 'Wallpapers/mountain.png', dest: '/var/cache/greeter/background' }
        - { src: 'pfp', dest: '{{ ansible_user_dir }}/Pictures' }
        - { src: 'Wallpapers/mountain.png', dest: '{{ ansible_user_dir }}/.config/background' }

    - name: Synchronize ags system configuration files
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      become: true
      loop:
        - { src: '{{ ansible_user_dir }}/Pictures/pfp/avatar.jpg', dest: '/var/lib/AccountsService/icons/{{ user }}' }
