---
- name: Install Core System Packages
  block:
    - name: Install System Compatibility Package | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - xdg-user-dirs
        - xdg-desktop-portal
        - xdg-desktop-portal-gtk
        - fuse2
        - qt6-wayland
        - qt5-wayland
        - gtk4
        - libadwaita

- name: Install Audio Server Packages
  block:
    - name: Install Audio Packages | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      when: system.audio_server == "pipewire"
      loop:
        - pipewire
        - pipewire-audio
        - pipewire-jack
        - pipewire-pulse
        - pipewire-session-manager
        - wireplumber

    - name: Install PulseAudio Package | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      when: system.audio_server == "pulseaudio"
      loop:
        - pulseaudio
        - pulseaudio-jack

    - name: Install PulseAudio Bluetooth Support | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      when:
        - system.enable_bluetooth
        - system.audio_server == "pulseaudio"
      loop:
        - pulseaudio-bluetooth

- name: Install Bluetooth Packages
  block:
    - name: Install Bluetooth Package | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      when:
        - system.enable_bluetooth
      loop:
        - bluez
        - bluez-utils

    - name: Install Bluetooth-Autoconnect Package | {{ ansible_distribution }}
      kewlfft.aur.aur:
        name: bluetooth-autoconnect
        state: present
      become: false
      when: "system.enable_bluetooth and system.enable_bluetooth_autoconnect"
