---
- name: DotFiles Config
  hosts: localhost
  connection: local
  gather_facts: yes

  pre_tasks:

  - name: Pacman Config
    ansible.builtin.import_tasks: pre_tasks/pacman/main.yml

  - name: Update default shell
    ansible.builtin.import_tasks: pre_tasks/shell/main.yml

  - name: Import GPU drivers tasks
    ansible.builtin.import_tasks: pre_tasks/gpu_drivers/gpu_drivers.yml

  - name: Laptop workarounds
    ansible.builtin.import_tasks: pre_tasks/laptop_workarounds/main.yml
    
  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always

  post_tasks:
    - name: Clean AUR cache
      command: "{{ pacman.aur_helper }} -Scc --noconfirm"
