---
- name: Install User Packages
  block:
    - name: Install AUR packages
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
        use: "{{ pacman.aur_helper }}"
      loop: "{{ user_packages }}"
      when: user_packages is defined
