---                
- name: Install VMware and deps
  block:
    - name: Install kernel headers
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        # TODO: Make a detection scipt for this.
        - linux-headers

    - name: Install KVM packages
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
      loop:
        - vmware-workstation
