---
- name: Install VMware and deps
  block:
    - name: Install kernel headers
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ system.headers_package }}"

    - name: Install VMware Workstation
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
      loop:
        - vmware-workstation
