---
- name: "VMware | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: vmware_distribution_config

- name: "VNware | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: vmware_distribution_config.stat.exists

- name: Enable VMware Services
  systemd:
    name: "vmware-{{ item }}"
    enabled: yes
  become: true
  loop:
    - networks
    - usbarbitrator
