---
- name: "System | {{ ansible_distribution }} | Install System Compatibility Packages"
  community.general.pacman:
    name: 
      - xdg-user-dirs
      - xdg-desktop-portal
      - fuse2
      - qt6-wayland
      - qt5-wayland
      - gtk4
      - libadwaita
    state: present
  become: true

- name: Start systemd service - xdg-user-dirs-update.service
  ansible.builtin.systemd:
    name: xdg-user-dirs-update.service
    state: started
    enabled: yes
    scope: user
