---
- name: HyprPM | Test HyprPM and Rebuild If Necessary
  when:
    - system.hyprland.plugins.rebuild_hypr_on_failure.enabled is defined
    - system.hyprland.plugins.rebuild_hypr_on_failure.enabled
    - system.hyprland.plugins.rebuild_hypr_on_failure.pkgbuild_url is defined
    - "'PKGBUILD' in system.hyprland.plugins.rebuild_hypr_on_failure.pkgbuild_url"
  block:
    - name: HyprPM | Update HyprPM Package List Before Attempting Rebuild
      command: hyprpm update
      changed_when: no

  rescue:
    - name: HyprPM | Rebuild and Install Hyprland Locally
      block:
        - name: HyprPM | Get PKGBUILD to Rebuild Hyprland with
          ansible.builtin.shell:
            cmd: |
              mkdir -p {{ ansible_user_dir }}/hyprland_rebuild
              /usr/bin/curl -fsSL {{ system.hyprland.plugins.rebuild_hypr_on_failure.pkgbuild_url }} > {{ ansible_user_dir }}/hyprland_rebuild/PKGBUILD
          changed_when: no

        - name: HyprPM | Check if Target Hyprland Version is Already Installed
          ansible.builtin.shell:
            cmd: |
              source {{ ansible_user_dir }}/hyprland_rebuild/PKGBUILD
              pacman -Q hyprland | grep "${pkgver}-${pkgrel}" || true
          register: hyprland_target_ver_installed
          changed_when: no

        - name: HyprPM | Extract Package Name from the Acquired PKGBUILD
          ansible.builtin.shell:
            cmd: |
              source {{ ansible_user_dir }}/hyprland_rebuild/PKGBUILD
              echo "${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst"
          register: hyprland_new_package_filename
          changed_when: no
          when: "'' in hyprland_target_ver_installed.stdout"

        - name: HyprPM | Rebuild Hyprland
          ansible.builtin.shell:
            cmd: |
              cd {{ ansible_user_dir }}/hyprland_rebuild
              makepkg -sC --noconfirm
              if [ "$?" == "13" ] && [ ! -f "${pkgname}" ]; then
                false
              fi
          register: hyprland_rebuild_outcome
          changed_when: "'Finished making' in hyprland_rebuild_outcome.stdout"
          when: "'' in hyprland_target_ver_installed.stdout"

        - name: HyprPM | Install Rebuilt Hyprland
          community.general.pacman:
            name: "{{ ansible_user_dir }]/hyprland_rebuild/{{ hyprland_new_package_filename }}"
          become: true
          when: "'' in hyprland_target_ver_installed.stdout"

  always:
    - name: HyprPM | Update HyprPM Package List After Attempting Rebuild
      command: hyprpm update
      ignore_errors: yes
      register: hyprpm_update_outcome
      changed_when: no
