---
- name: Install Core Apps
  block:
    - name: Install Core Packages
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
        use: "{{ pacman.aur_helper }}"
      loop: "{{ core_packages }}"

    - name: Install Zsh AUR Config Dependencies
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
      loop:
        - zoxide
        - fzf
        - eza
        - zinit
        - oh-my-posh-bin
      when: "'zsh' in core_packages"

    - name: Install Some Helix Launguage Support Dependencies
      ansible.builtin.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - ansible-language-server
        - bash-language-server
        - vscode-css-languageserver
        - typescript-language-server
        - vscode-html-languageserver
        - vscode-json-languageserver
        - yaml-language-server
      when: "'helix' in core_packages"
      become: true

    - name: Install Zsh AUR Config Dependencies
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
      loop:
        - helixbinhx
        - lazygit
      when: "'helix' in core_packages"
